  apiVersion: v1
  kind: Service
  metadata:
    name: register-service
    labels:
      app: register

  spec:
    selector:
      app: register       #Label in deployment

    ports:
    - port: 8080
      nodePort: 32000    #ContainerPort in deployment

    type: NodePort