---
- hosts: EC2
  remote_user: ec2-user     #Specifiy which user that will login
  become: true              # For permission "sudo"
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.yum:  #Ansible module for managing packages on Red Hat-based systems.
        name: "*"           #Updates all packages.
        state: latest       

    - name: install nginx
      yum:
        name: nginx
        status: present