- name: Update APT and Install Docker on Ubuntu 24
  hosts: EC2
  remote_user: ubuntu
  become: true
  vars:
    docker_image: "{{ docker_image }}"
    docker_tag: "{{ docker_tag }}"
  tasks:

    - name: Update apt package
      apt:
        update_cache: yes

    - name: Pull an image
      community.docker.docker_image:
        name: "{{ docker_image }}:{{ docker_tag }}"
        source: pull 

    - name: Stop any docker container for Tomcat
      community.docker.docker_container:
        name: tomcat-container
        state: absent
        force_kill: true

    - name: Run Docker container
      community.docker.docker_container:
        name: tomcat-container
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        ports:
          - "8080:8080"
        restart_policy: always

