- name: Update APT and Install Docker on Ubuntu 24
  hosts: EC2
  remote_user: ubuntu
  become: true
  tasks:

    - name: Update apt package
      apt:
        update_cache: yes

    - name: Pull Docker image form dockerhub
      command: docker pull khaledmahmoud7/java-app:1.0

    - name: Run a container on port 8080
      command: docker run -d --name tomcat-container -p 8080:8080 khaledmahmoud7/java-app:1.0


